---
title: "rdm-explore-objects"
author: "Bria Long"
date: "2025-12-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(langcog)
```

Low precision categories from Jane
```{r}
exclude_low_precision = read_csv('low_precision.txt', col_names=FALSE)
```

# Load embeddings
```{r}
embeddings_things_dino <- read_csv(here::here('data/embeddings/things_dino_embeddings.csv'))  %>%
  rename(category = 1) %>%
  filter(!category %in% exclude_low_precision$X1)  %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  mutate(category = as.factor(category)) %>%
  arrange(-desc(category))
```

```{r}
embeddings_things_clip <- read_csv(here::here('data/embeddings/things_clip_embeddings.csv'))  %>%
  rename(category = 1) %>%
  filter(!category %in% exclude_low_precision$X1)  %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  mutate(category = as.factor(category)) %>%
  arrange(-desc(category))

filtered_categories = unique(embeddings_things_clip$category)
```

```{r}
embeddings_babyview_clip <- read_csv(here::here('data/embeddings/babyview_clip_filtered26_category_average_embeddings.csv'))  %>%
  rename(category = 1) %>%
  filter(!category %in% exclude_low_precision$X1)  %>%
  filter(category %in% filtered_categories) %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  mutate(category = as.factor(category)) %>%
  arrange(-desc(category))



```
Sanity check
```{r}
alligator = as.numeric(embeddings_babyview_clip %>% filter(category=='alligator'))

deer = as.numeric(embeddings_babyview_clip %>% filter(category=='deer'))
deer_things = as.numeric(embeddings_things_clip %>% filter(category=='deer'))



cosine_distance <- function(x, y) {
  1 - sum(x * y) / (sqrt(sum(x^2)) * sqrt(sum(y^2)))
}

#
pearsons_distance_sanity = 1 - cor(deer[2:513], alligator[2:513])
cosine_distance_sanity = cosine_distance(deer[2:513], alligator[2:513])

```


```{r}
embeddings_babyview_dino <- read_csv(here::here('data/embeddings/babyview_dinov3_filtered26_category_average_embeddings.csv'))  %>%
  rename(category = 1) %>%
  filter(category %in%filtered_categories) %>%
  filter(!category %in% exclude_low_precision$X1) %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  mutate(category = as.factor(category)) %>%
  arrange(-desc(category))
```


## Functions for making rdms
```{R}
# Cosine distance helper
cosine_distance <- function(x, y) {
  1 - sum(x * y) / (sqrt(sum(x^2)) * sqrt(sum(y^2)))
}

pearson_distance <- function(x, y) {
  # x and y are numeric vectors of equal length
  r <- cor(x, y, method = "pearson", use = "pairwise.complete.obs")
  1 - r
}

makeLongRDM <- function(embeddings,distance_metric) {
  
  categories <- embeddings$category
  emb_matrix <- embeddings %>%
    select(starts_with("dim_")) %>%
    as.matrix()
  
  # Cosine RDM as an n x n matrix
  rdm_cosine_mat <- outer(
    1:nrow(emb_matrix),
    1:nrow(emb_matrix),
    Vectorize(function(i, j) distance_metric(emb_matrix[i, ], emb_matrix[j, ]))
  )

  dimnames(rdm_cosine_mat) <- list(categories, categories)

  # Tidy long version (great for ggplot / RSA)
  rdm_cosine_long <- as_tibble(rdm_cosine_mat, rownames = "category1") %>%
  pivot_longer(
    cols = -category1,
    names_to = "category2",
    values_to = "distance"
  )
  
  return(rdm_cosine_long)
}


makeRDM <- function(embeddings,distance_metric) {
  
  categories <- embeddings$category
  emb_matrix <- embeddings %>%
    select(starts_with("dim_")) %>%
    as.matrix()
  
    row_norms <- sqrt(rowSums(emb_matrix^2))
    emb_norm  <- emb_matrix / row_norms

   # cosine *similarity* RDM
   cosine_sim_rdm <- tcrossprod(emb_norm)   

   # cosine *distance* RDM (1 - similarity)
   cosine_dist_rdm <- 1 - cosine_sim_rdm
   dimnames(cosine_dist_rdm) <- list(categories, categories)
  
  return(cosine_dist_rdm)
}

```


```{r}
babyview_dino_mat <- makeRDM(embeddings_babyview_dino)
babyview_clip_mat <- makeRDM(embeddings_babyview_clip)
things_clip_mat <- makeRDM(embeddings_things_clip)
things_dino_mat <- makeRDM(embeddings_things_dino)
```


```{r}
babyview_dino <- makeLongRDM(embeddings_babyview_dino,pearson_distance)
babyview_clip <- makeLongRDM(embeddings_babyview_clip,pearson_distance)
things_clip <- makeLongRDM(embeddings_things_clip,pearson_distance)
things_dino <- makeLongRDM(embeddings_things_dino,pearson_distance)
```


```{r}
assertthat::assert_that( sum(!babyview_clip$category1==babyview_dino$category1)==0)
assertthat::assert_that( sum(!things_dino$category1==babyview_dino$category1)==0)
assertthat::assert_that( sum(!things_clip$category1==things_dino$category1)==0)
assertthat::assert_that( sum(!babyview_clip$category1==things_clip$category1)==0)


```

# Compare RDMs
```{r}
cor.test(babyview_clip_mat[upper.tri(babyview_clip_mat)],things_clip_mat[upper.tri(things_clip_mat)], method='spearman')
```

```{r}

```


```{r}
cor.test(babyview_dino_mat[upper.tri(babyview_dino_mat)],things_dino_mat[upper.tri(things_dino_mat)], method='spearman')
```


Babyview Dino vs CLIP is .88
```{r}
cor.test(babyview_dino_mat[upper.tri(babyview_dino_mat)],babyview_clip_mat[upper.tri(babyview_clip_mat)], method='spearman')
```
THINGS Dino vs CLIP is .46??
```{r}
cor.test(things_dino_mat[upper.tri(things_dino_mat)],things_clip_mat[upper.tri(things_clip_mat)], method='spearman')
```


```{r}
makeLongOrderedRDM <- function(rdm_cosine_long){
# Make a wide matrix again for clustering
rdm_mat <- rdm_cosine_long %>%
  pivot_wider(
    names_from = category2,
    values_from = distance
  ) %>%
  column_to_rownames("category1") %>%
  as.matrix()

# Hierarchical clustering order
hc <- hclust(as.dist(rdm_mat))
ord <- rownames(rdm_mat)[hc$order]

rdm_cosine_long_ordered <- rdm_cosine_long %>%
  mutate(
    category1 = factor(category1, levels = ord),
    category2 = factor(category2, levels = ord)
  )
}
```

```{r}
babyview_clip_ordered <- makeLongOrderedRDM(babyview_clip)
ordered_categories = levels(babyview_clip_ordered$category1)
```

Make ordered RDMs
```{r}
babyview_dino_ordered <- babyview_dino %>%
  mutate(
    category1 = factor(category1, levels = ordered_categories),
    category2 = factor(category2, levels = ordered_categories)
  )

things_dino_ordered <- things_dino %>%
  mutate(
    category1 = factor(category1, levels = ordered_categories),
    category2 = factor(category2, levels = ordered_categories)
  )

things_clip_ordered <- things_clip %>%
  mutate(
    category1 = factor(category1, levels = ordered_categories),
    category2 = factor(category2, levels = ordered_categories)
  )

```


```{r}
ggplot(babyview_clip_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "CLIP category RDM (cluster-ordered)"
  )

ggsave('babyview-clip-ordered.pdf', width=8, height=8, units='in')
```
```{r}
ggplot(babyview_dino_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "DINO category RDM (clip cluster-ordered)"
  )

ggsave('babyview-dino-ordered.pdf', width=6, height=6, units='in')
```

```{r}
ggplot(things_dino_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
   # ylim(0,1.8) +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "THINGS Dino category RDM (CLIP cluster-ordered)"
  )

ggsave('things-dino-ordered.pdf', width=6, height=6, units='in')
```

```{r}
ggplot(things_clip_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
  # ylim(0,1.8) +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "Things CLIP category RDM (CLIP cluster-ordered)"
  )

ggsave('things-clip-ordered.pdf', width=6, height=6, units='in')
```



## category variablity

```{r}
row_correlation_matrix <- function(A, B) {
  A <- A %>% select(-category)
  B <- B %>% select(-category)
  A <- as.matrix(A)
  B <- as.matrix(B)
  stopifnot(ncol(A) == ncol(B))

  # center each row by its own mean
  A_center <- A - rowMeans(A)
  B_center <- B - rowMeans(B)

  # row-wise L2 norms of centered rows (proportional to SD)
  A_norm <- sqrt(rowSums(A_center^2))
  B_norm <- sqrt(rowSums(B_center^2))

  # avoid division by zero
  A_center <- A_center / A_norm
  B_center <- B_center / B_norm

  # all-pairs row correlations: (n1 x d) %*% (d x n2) -> n1 x n2
  A_center %*% t(B_center)
}
```

```{R}
categories <- embeddings_babyview_clip$category
corr_matrix_clip = row_correlation_matrix(embeddings_babyview_clip, embeddings_things_clip)
dimnames(corr_matrix_clip) <- list(categories, categories)

corr_matrix_dino = row_correlation_matrix(embeddings_babyview_dino, embeddings_things_dino)
dimnames(corr_matrix_dino) <- list(categories, categories)


```


```{r}
corr_long_clip <- corr_matrix_clip |>
  as.data.frame() |>
  rownames_to_column("category1") |>
  pivot_longer(
    cols = -category1,
    names_to = "category2",
    values_to = "correlation"
  ) %>%
  mutate(model='clip')

corr_long_dino <- corr_matrix_dino |>
  as.data.frame() |>
  rownames_to_column("category1") |>
  pivot_longer(
    cols = -category1,
    names_to = "category2",
    values_to = "correlation"
  ) %>%
  mutate(model='dino')
```

Most and least similar in clip
```{r}
most_similar <- corr_long %>%
  filter(category1==category2) %>%
  slice_max(correlation, n=10)

least_similar <- corr_long %>%
  filter(category1==category2) %>%
  slice_min(correlation, n=10)
```

```{r}
## sanity check
deer = as.numeric(embeddings_babyview_clip %>% filter(category=='deer'))
deer_things = as.numeric(embeddings_things_clip %>% filter(category=='deer'))
cor.test(deer[2:513], deer_things[2:513])


sanity <- corr_long %>%
  filter(category1=='deer') %>%
  filter(category1==category2)
```


```{r}
ordered_similarity <- corr_long_clip %>%
  full_join(corr_long_dino) %>%
  filter(category1==category2) %>%
  arrange(correlation, desc=TRUE) %>%
  group_by(model) %>%
  mutate(category1 = fct_reorder(category1, -correlation)) %>%
  pivot_wider(names_from='model', values_from="correlation") %>%
  select(-category2) 
```
```{r}
colors = read_csv('color_categories.csv') %>%
  as_tibble()  %>%
  rename(category1 = item, group = category)

ordered_similarity <- ordered_similarity %>%
  left_join(colors)
```
```{r}
library(ggthemes)
ggplot(ordered_similarity, aes(x = clip, y = dino, col=group)) +
  geom_point() +
  theme_few(base_size=6) +
  ggrepel::geom_label_repel(aes(label=category1), box.padding = 0.3,
    point.padding = 0.2,
    size = 2,
    max.overlaps = 20) +
  ylim(0,1) +
  xlim(0,1) +
  xlab('Similarity in CLIP (Babyview vs THINGS)') +
  ylab('Similarity in DINO (Babyview vs THINGS)') +
  facet_wrap(~group, nrow=2)
  
ggsave('similarity_comparison.pdf', width=8, height=4, unit='in')
  
 
```