---
title: "rdm-explore-objects"
author: "Bria Long"
date: "2025-12-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(langcog)
```

Low precision categories from Jane
```{r}
exclude_low_precision = read_csv('low_precision.txt', col_names=FALSE)
```

# Load embeddings
```{r}
embeddings_things_dino <- read_csv(here::here('data/embeddings/things_dino_embeddings.csv'))  %>%
  rename(category = 1) %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  filter(!category %in% exclude_low_precision$X1)
```

```{r}
embeddings_things_clip <- read_csv(here::here('data/embeddings/things_clip_embeddings.csv'))  %>%
  rename(category = 1) %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  filter(!category %in% exclude_low_precision$X1)  %>%
  mutate(category = as.factor(category)) %>%
  arrange(-desc(category))

filtered_categories = unique(embeddings_things_clip$category)
```

```{r}
embeddings_babyview_clip <- read_csv(here::here('data/embeddings/babyview_clip_filtered26_category_average_embeddings.csv'))  %>%
  rename(category = 1) %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  filter(category %in%filtered_categories) %>%
  filter(!category %in% exclude_low_precision$X1) %>%
   mutate(category = as.factor(category)) %>%
  arrange(-desc(category))

```

```{r}
embeddings_babyview_dino <- read_csv(here::here('data/embeddings/babyview_dinov3_filtered26_category_average_embeddings.csv'))  %>%
  rename(category = 1) %>%
  rename_with(
    .cols = where(is.numeric),
    .fn   = ~ paste0("dim_", seq_along(.x))
  )  %>%
  mutate(
    across(
      .cols = where(is.numeric) & !matches("category"),
      .fns  = ~ as.numeric(scale(.x))
    )
  ) %>%
  filter(category %in%filtered_categories) %>%
  filter(!category %in% exclude_low_precision$X1) %>%
   mutate(category = as.factor(category)) %>%
  arrange(-desc(category))
```


## Functions for making rdms
```{R}
# Cosine distance helper
cosine_distance <- function(x, y) {
  1 - sum(x * y) / (sqrt(sum(x^2)) * sqrt(sum(y^2)))
}

pearson_distance <- function(x, y) {
  # x and y are numeric vectors of equal length
  r <- cor(x, y, method = "pearson", use = "pairwise.complete.obs")
  1 - r
}

makeLongRDM <- function(embeddings,distance_metric) {
  
  categories <- embeddings$category
  emb_matrix <- embeddings %>%
    select(starts_with("dim_")) %>%
    as.matrix()
  
  # Cosine RDM as an n x n matrix
  rdm_cosine_mat <- outer(
    1:nrow(emb_matrix),
    1:nrow(emb_matrix),
    Vectorize(function(i, j) distance_metric(emb_matrix[i, ], emb_matrix[j, ]))
  )

  dimnames(rdm_cosine_mat) <- list(categories, categories)

  # Tidy long version (great for ggplot / RSA)
  rdm_cosine_long <- as_tibble(rdm_cosine_mat, rownames = "category1") %>%
  pivot_longer(
    cols = -category1,
    names_to = "category2",
    values_to = "distance"
  )

  return(rdm_cosine_long)
  
}

```


```{r}
babyview_dino <- makeLongRDM(embeddings_babyview_dino,cosine_distance)
babyview_clip <- makeLongRDM(embeddings_babyview_clip,cosine_distance)
things_clip <- makeLongRDM(embeddings_things_clip,cosine_distance)
things_dino <- makeLongRDM(embeddings_things_dino,cosine_distance)
```


# Compare RDMs

Babyview vs THINGS
```{r}
cor.test(babyview_clip$distance, things_clip$distance, method='spearman')
```

Babyview vs THINGS in DINO
```{r}
cor.test(babyview_dino$distance, things_dino$distance, method='spearman')
```


Babyview clip vs dino
```{r}
cor.test(babyview_clip$distance, babyview_dino$distance, method='spearman')
```

THINGS clip vs dino
```{r}
cor.test(things_clip$distance, things_dino$distance, method='spearman')
```


```{r}
makeLongOrderedRDM <- function(rdm_cosine_long){
# Make a wide matrix again for clustering
rdm_mat <- rdm_cosine_long %>%
  pivot_wider(
    names_from = category2,
    values_from = distance
  ) %>%
  column_to_rownames("category1") %>%
  as.matrix()

# Hierarchical clustering order
hc <- hclust(as.dist(rdm_mat))
ord <- rownames(rdm_mat)[hc$order]

rdm_cosine_long_ordered <- rdm_cosine_long %>%
  mutate(
    category1 = factor(category1, levels = ord),
    category2 = factor(category2, levels = ord)
  )
}
```

```{r}
babyview_clip_ordered <- makeLongOrderedRDM(babyview_clip)
ordered_categories = levels(babyview_clip_ordered$category1)
```

Make ordered RDMs
```{r}
babyview_dino_ordered <- babyview_dino %>%
  mutate(
    category1 = factor(category1, levels = ordered_categories),
    category2 = factor(category2, levels = ordered_categories)
  )

things_dino_ordered <- things_dino %>%
  mutate(
    category1 = factor(category1, levels = ordered_categories),
    category2 = factor(category2, levels = ordered_categories)
  )

things_clip_ordered <- things_clip %>%
  mutate(
    category1 = factor(category1, levels = ordered_categories),
    category2 = factor(category2, levels = ordered_categories)
  )

```


```{r}
ggplot(babyview_clip_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "CLIP category RDM (cluster-ordered)"
  )

ggsave('babyview-clip-ordered.pdf', width=6, height=6, units='in')
```
```{r}
ggplot(babyview_dino_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "DINO category RDM (clip cluster-ordered)"
  )

ggsave('babyview-dino-ordered.pdf', width=6, height=6, units='in')
```

```{r}
ggplot(things_dino_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
   # ylim(0,1.8) +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "THINGS Dino category RDM (CLIP cluster-ordered)"
  )

ggsave('things-dino-ordered.pdf', width=6, height=6, units='in')
```

```{r}
ggplot(things_clip_ordered, aes(x = category1, y = category2, fill = distance)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  coord_equal() +
  # ylim(0,1.8) +
  # theme_minimal(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=4),
    axis.text.y = element_text(hjust = 1, vjust = 1, size=4),
    panel.grid = element_blank()
  ) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Cosine distance",
    title = "Things CLIP category RDM (CLIP cluster-ordered)"
  )

ggsave('things-clip-ordered.pdf', width=6, height=6, units='in')
```